services:
  db:
    image: "mariadb:11"
    ports:
      - "3390:3306"
    expose:
      - "3390"
    volumes:
      - "./schema:/docker-entrypoint-initdb.d"
    environment:
      MARIADB_ROOT_PASSWORD: root-pw
      MARIADB_DATABASE: chitchat
      MARIADB_USER: chitchat
      MARIADB_PASSWORD: password
#  app:
#    build: .